@startuml

actor Usuário

Usuário -> Sistema: registerActivity()
activate Sistema
Sistema --> Usuário: registerActivityScreen()
Usuário -> Sistema: Duração da atividade
Usuário -> Sistema: Localização da atividade
loop while has next participant
Usuário -> Sistema: Participante da atividade
end
Usuário -> Sistema: Objetivo da atividade
Usuário -> Sistema: Descrição da atividade
Sistema --> Usuário: Atividade cadastrada com sucesso!
deactivate Sistema

@enduml
