@startuml
rectangle User
rectangle "ctrl : RegisterMemberCtrl" as Ctrl
rectangle "view : RegisterMemberView" as View
rectangle "repo : MemberRepository" as Repo
rectangle "Member" as Member
rectangle "mb : MemberBuilder" as Builder
rectangle "m : Member" as Mem

User --(Ctrl): \n1: registerMember() <&arrow-bottom>

Ctrl --(View): \n2: showMemberRegistrationView() \n3: name = getName() \n4: cpf = getCpf() \n5: [member == null] rg = getRG() \n6: email = getEmail() \n7: phone = getPhone() \n8: department = getDepartment() \n9: course = getCourse() \n10: birthDate = getBirthDate() \n11: showConfirmation() \n19: showSuccess() \n20: [member != null] showError() <&arrow-bottom>

Ctrl --(Repo): \n12: member = findMember(cpf) \n18: [member == null] addRepo(m) <&arrow-bottom>

Ctrl --(Member): \n13: mb = builder() <&arrow-bottom>

Member --(Builder): \n14: mb = new MemberBuilder() <&arrow-bottom>

Ctrl --(Builder): \n15: name(name) \n16: rg(rg) \n17: email(email) \n18: phone(phone) \n19: department(department) \n20: course(course) \n21: birthDate(birthDate) \n22: m = build() <&arrow-bottom>

Builder --(Mem): \n23: m = new Member() <&arrow-bottom>
@enduml
