@startuml
rectangle User
rectangle "devCtrl : DevCtrl" as Ctrl
rectangle "view : DevView" as View
rectangle "dr : DevRepository" as DevRepo
rectangle "pr : ProjectRepository" as ProjRepo
rectangle "mr : MemberRepository" as MemberRepo
rectangle "dev : Dev" as Dev
rectangle "p : Project" as Project

User --(Ctrl): \n1: addDevToProject() <&arrow-bottom>

Ctrl --(View): \n2: showAddDevToProjectScreen() \n3: devName = getDevName() \n4: projName = getProjName() \n 8.1 [p.isEmpty()] showError() <&arrow-bottom>
Ctrl --(Ctrl): \n5: addDevToProject(devName, projName)\n 7.1: [!p.isEmpty()]addDevToProject(devName, p)\n 7.3.1 [!m.isEmpty()] dev = findDev(devName) \n 7.3.2: [m.isEmpty()] showError() <&arrow-bottom>
Ctrl --(ProjRepo): \n6: p = findProject(projName) <&arrow-bottom>
Ctrl --(MemberRepo): \n 7.2: m = findMember(devName) <&arrow-bottom>
Ctrl --(Dev): \n 7.3.1.2: dev = new Dev(m, p) <&arrow-bottom>
Ctrl --(DevRepo): \n 7.3.1.3: addDev(dev) <&arrow-bottom>
Ctrl --(Project): \n 7.3.1.4: addDev(dev) <&arrow-bottom>

@enduml

